### PR TITLE
Better handling of python3 deps for packaging

### PR DESCRIPTION
**Pull request by free-x**
Hi @sailoog ,

this PR propose better handling of python3 dependencies

Greetings
free-x

### CODE REVIEW

**Comment by sailoog** [comment]
I see the advantages of this way: 
- python dependencies will be auto-installed by pip3 and you do not need to install them manually as debian packages before installing openplotter-settings.
- pip3 packages have better compatibility between different debian derivatives than packages from the different repositories (debian, ubuntu, raspberry OS...)

But this also creates some questions and disadvantages:
- should not we add pip3 as debian dependency?
- debian packages are  updated with "apt update" but pip packages are not.
- debian packages will be uninstalled when you uninstall the dependent packages a no more packages need them. pip packages will remain.

Currently openplotter apps prioritize debian packages over pip packages for these reasons and they use pip only when a package is not common for all repositories (debian, ubuntu, raspberry OS...)

**Comment by free-x** [comment]
pip3 is not needed for packages. 
Advantage:
${python3:Depends} conciders automatic python modules that provides by setup.py

Greetings
free-x

**Comment by sailoog** [comment]
ops, then I may have not understood how this works. Where these packages come from? how are they updated and uninstalled?

**Comment by free-x** [comment]
small background
https://stackoverflow.com/questions/37481583/what-does-python3depends-mean-in-a-debian-source-package-control-file

**Comment by free-x** [comment]
I'm afraid.... i see one regression. Don't know why, but Macro doesn't work with python3-wxgtk4.0

**Comment by sailoog** [comment]
So, they are debian packages at the end and I was wrong. Let me play with this before merging. Thanks!

**Pull request merged**
